#!/usr/bin/env bash
# This script audits DNS records for specified subdomains of a domain.
# Function to display subdomain information
display_subdomain_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    local destination=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        display_subdomain_info $sub $domain
    done
else
    display_subdomain_info $subdomain $domain
fi
