#!/usr/bin/env bash
# This script audits DNS records for specified subdomains of a domain.

# Function to display subdomain information
display_subdomain_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    local destination=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # Define subdomains with their corresponding IPs
    subdomains=("www" "lb-01" "web-01" "web-02")
    ip_map=("18.208.223.205" "18.208.223.205" "54.83.87.119" "18.204.231.167")
    
    # Display subdomain information
    for ((i=0; i<${#subdomains[@]}; i++)); do
        echo "The subdomain ${subdomains[$i]} points to ${ip_map[$i]}"
    done
else
    display_subdomain_info $subdomain $domain
fi
